apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: xxl-job
spec:
  ports:         
    - port: 3306
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql-service
  namespace: xxl-job
subsets:
  - addresses:
      - ip: 192.168.0.140        #外部实体服务hostname
    ports:
      - port: 3306               #外部实体服务port
