apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: xxl-job-admin
  namespace: xxl-job
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xxl-job-admin
  minReplicas: 1
  maxReplicas: 1  
  metrics:
  - type: Resource
    resource:                          
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:                          
      name: memory            
      targetAverageUtilization: 70